# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 3
  port: 8082
  connection-timeout: 50000ms
  servlet:
    context-path: /

#spring
spring:
  application:
    name: multi-module-web
  devtools:
    restart:
      enabled: true
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  # 环境 dev|test|prod
  profiles:
    active: dev

# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
#  type-aliases-package: com.ck.multimodule.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: "null"

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

com:
  filePath:
    img: D:/image/